env:
  browser: true
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
rules:
  semi:
    - error
    - always
  quotes:
    - error
    - single
  'prettier/prettier':
    - error
    - singleQuote: true
      tabWidth: 3
      trailingComma: "es5"
